packages:
  - apps/*
  - modules/*
  - identity-apps-core
  - features
  - features/*
catalog:
  "@artsy/fresnel": ^6.1.0
  "@babel/cli": ^7.10.5
  "@babel/plugin-proposal-class-properties": ^7.10.4
  "@babel/plugin-proposal-decorators": ^7.10.5
  "@babel/plugin-transform-modules-commonjs": ^7.10.4
  "@babel/polyfill": ^7.0.0
  "@babel/preset-env": ^7.11.0
  "@babel/preset-react": ^7.14.5
  "@babel/preset-typescript": ^7.10.4
  "@babel/register": ^7.8.6
  "@babel/runtime-corejs3": ^7.11.2
  "@braintree/sanitize-url": ^5.0.0
  "@changesets/changelog-github": ^0.4.8
  "@changesets/cli": ^2.26.1
  "@emotion/react": ^11.11.0
  "@emotion/styled": ^11.11.0
  "@microsoft/applicationinsights-core-js": ^3.0.0
  "@microsoft/applicationinsights-react-js": ^3.4.2
  "@microsoft/applicationinsights-web": ^3.0.0
  "@monaco-editor/react": ^4.5.1
  "@mui/icons-material": ^5.11.16
  "@mui/lab": 5.0.0-alpha.129
  "@mui/material": ^5.13.0
  "@mui/system": ^5.12.3
  "@mui/utils": ^5.12.3
  "@nx/devkit": 17.0.0
  "@nx/jest": 17.0.0
  "@nx/js": 17.0.0
  "@nx/plugin": 17.0.0
  "@nx/react": 17.0.0
  "@nx/rollup": 17.0.0
  "@nx/storybook": 17.0.0
  "@nx/web": 17.0.0
  "@nx/webpack": 17.0.0
  "@nx/workspace": 17.0.0
  "@oxygen-ui/react-icons": ^1.13.6
  "@rollup/plugin-image": ^3.0.3
  "@rollup/plugin-json": ^6.1.0
  "@rollup/plugin-typescript": ^11.1.6
  "@rollup/plugin-url": ^7.0.0
  "@storybook/addon-actions": ^6.5.12
  "@storybook/addon-backgrounds": ^6.5.12
  "@storybook/addon-controls": ^6.5.12
  "@storybook/addon-docs": ^6.5.12
  "@storybook/addon-links": ^6.5.12
  "@storybook/addon-measure": ^6.5.12
  "@storybook/addon-outline": ^6.5.12
  "@storybook/addon-toolbars": ^6.5.12
  "@storybook/addon-viewport": ^6.5.12
  "@storybook/addons": ^6.5.9
  "@storybook/builder-webpack5": ^6.5.9
  "@storybook/manager-webpack5": ^6.5.9
  "@storybook/react-webpack5": 7.6.9
  "@storybook/theming": ^6.5.9
  "@svgr/rollup": ^6.2.1
  "@swc-node/register": 1.6.8
  "@swc/cli": 0.1.65
  "@swc/core": 1.3.99
  "@swc/helpers": 0.5.9
  "@testing-library/react": ^14.2.1
  "@types/crypto-js": ^3.1.43
  "@types/file-saver": ^2.0.1
  "@types/history": ^4.7.3
  "@types/i18next": 8.4.3
  "@types/i18next-xhr-backend": ^1.4.2
  "@types/js-beautify": ^1.8.2
  "@types/js-yaml": 3.12.3
  "@types/lodash-es": ^4.17.4
  "@types/node-forge": ^0.9.3
  "@types/react": ^18.0.18
  "@types/react-color": ^3.0.6
  "@types/react-dom": ^18.0.6
  "@types/react-notification-system": 0.2.39
  "@types/react-redux": ^7.1.25
  "@types/react-router": ^5.1.18
  "@types/react-router-dom": ^5.1.3
  "@types/reactour": ^1.18.1
  "@types/redux-mock-store": ^1.0.2
  "@types/testing-library__jest-dom": ^5.14.3
  "@types/ua-parser-js": 0.7.36
  "@types/uuid": ^9.0.1
  "@types/webappsec-credential-management": ^0.6.0
  "@types/webpack-env": ^1.16.0
  "@wso2is/admin.actions.v1": ^1.0.19
  "@wso2is/admin.administrators.v1": ^2.22.4
  "@wso2is/admin.alternative-login-identifier.v1": ^1.0.20
  "@wso2is/admin.api-resources.v1": ^2.20.132
  "@wso2is/admin.api-resources.v2": ^2.20.132
  "@wso2is/admin.application-templates.v1": ^1.0.20
  "@wso2is/admin.applications.v1": ^2.23.20
  "@wso2is/admin.authentication-flow-builder.v1": ^2.20.132
  "@wso2is/admin.authentication.v1": ^2.20.132
  "@wso2is/admin.authorization.v1": ^2.20.55
  "@wso2is/admin.branding.ai.v1": ^2.20.132
  "@wso2is/admin.branding.v1": ^2.20.132
  "@wso2is/admin.certificates.v1": ^2.20.132
  "@wso2is/admin.claims.v1": ^2.20.132
  "@wso2is/admin.connections.v1": ^2.21.62
  "@wso2is/admin.console-settings.v1": ^2.20.132
  "@wso2is/admin.core.v1": ^2.27.2
  "@wso2is/admin.email-and-sms.v1": ^2.20.132
  "@wso2is/admin.email-management.v1": ^2.20.132
  "@wso2is/admin.email-providers.v1": ^2.20.132
  "@wso2is/admin.email-templates.v1": ^2.20.132
  "@wso2is/admin.extensions.v1": ^2.24.5
  "@wso2is/admin.groups.v1": ^2.20.132
  "@wso2is/admin.home.v1": ^1.0.5
  "@wso2is/admin.identity-providers.v1": ^2.21.62
  "@wso2is/admin.identity-verification-providers.v1": ^2.20.132
  "@wso2is/admin.impersonation.v1": ^1.1.74
  "@wso2is/admin.login-flow.ai.v1": ^2.20.132
  "@wso2is/admin.logs.v1": ^1.0.7
  "@wso2is/admin.oidc-scopes.v1": ^2.20.132
  "@wso2is/admin.org-insights.v1": ^2.20.132
  "@wso2is/admin.organization-discovery.v1": ^2.20.132
  "@wso2is/admin.organizations.v1": ^2.21.25
  "@wso2is/admin.private-key-jwt.v1": ^2.20.132
  "@wso2is/admin.provisioning.v1": ^2.20.132
  "@wso2is/admin.remote-repository-configuration.v1": ^2.20.132
  "@wso2is/admin.roles.v1": ^2.20.132
  "@wso2is/admin.roles.v2": ^2.20.132
  "@wso2is/admin.saml2-configuration.v1": ^2.20.132
  "@wso2is/admin.secrets.v1": ^2.20.132
  "@wso2is/admin.server-configurations.v1": ^2.21.74
  "@wso2is/admin.server.v1": ^2.20.132
  "@wso2is/admin.session-management.v1": ^2.20.132
  "@wso2is/admin.sms-providers.v1": ^2.20.132
  "@wso2is/admin.subscription.v1": ^1.0.2
  "@wso2is/admin.template-core.v1": ^1.0.20
  "@wso2is/admin.tenants.v1": ^2.21.4
  "@wso2is/admin.username-validation.v1": ^1.0.20
  "@wso2is/admin.users.v1": ^2.21.4
  "@wso2is/admin.userstores.v1": ^2.20.132
  "@wso2is/admin.validation.v1": ^2.20.132
  "@wso2is/admin.workflow-approvals.v1": ^2.20.132
  "@wso2is/admin.wsfed-configuration.v1": ^2.20.132
  "@wso2is/common.ai.v1": ^2.20.132
  "@wso2is/common.branding.v1": ^2.20.132
  "@wso2is/dynamic-forms": ^2.0.95
  "@wso2is/form": ^2.1.3
  "@wso2is/i18n": ^2.5.23
  "@wso2is/react-components": ^2.4.2
  "@wso2is/theme": ^2.1.0
  "@wso2is/validation": ^2.0.9
  autoprefixer: 10.4.13
  await-semaphore: ^0.1.3
  babel-loader: ^8.1.0
  babel-plugin-rename-jsx-attribute: ^0.2.4
  babel-plugin-transform-es2015-modules-commonjs: ^6.26.2
  babel-polyfill: ^6.26.0
  child_process: ^1.0.2
  classnames: ^2.2.6
  clean-css: ^4.2.1
  codemirror: ^5.52.0
  compression-webpack-plugin: ^7.1.2
  connect-history-api-fallback: ^2.0.0
  copy-webpack-plugin: ^12.0.2
  core-js: ^3.6.5
  country-language: ^0.1.7
  crypto-js: ^3.1.9-1
  deep-equal: ^2.2.2
  dompurify: ^3.0.9
  dotenv: ^16.0.3
  eslint-config-prettier: 9.1.0
  eslint-plugin-import: ^2.20.2
  eslint-plugin-jest-dom: ^4.0.1
  eslint-plugin-jsonc: ^2.15.1
  eslint-plugin-jsx-a11y: 6.5.1
  eslint-plugin-react-hooks: ^4.0.0
  eslint-plugin-testing-library: ^5.0.5
  eslint-plugin-tsdoc: ^0.2.16
  extract-text-webpack-plugin: ^4.0.0-beta.0
  fast-xml-parser: ^3.15.0
  fastestsmallesttextencoderdecoder: ^1.0.22
  file-loader: ^2.0.0
  file-saver: ^2.0.5
  fork-ts-checker-webpack-plugin: ^6.1.0
  framer-motion: ^11.1.9
  fs-extra: ^9.0.1
  glob: ^7.1.3
  history: ^4.9.0
  html-react-parser: ^2.0.0
  html-webpack-plugin: ^5.2.0
  i18next: ^21.9.1
  i18next-browser-languagedetector: ^6.1.5
  i18next-xhr-backend: ^3.2.2
  identity-obj-proxy: ^3.0.0
  js-beautify: ^1.13.0
  js-yaml: 3.13.1
  jsonc-eslint-parser: ^2.1.0
  jsrsasign: ^10.5.26
  lerna: ^5.1.2
  less: ^3.10.3
  less-loader: ^5.0.0
  less-plugin-inline-urls: ^1.2.0
  less-plugin-npm-import: ^2.1.0
  less-plugin-rewrite-import: ^0.1.1
  less-plugin-rewrite-variable: 0.1.0
  less-to-json: ^1.2.0
  less-vars-to-js: ^1.3.0
  lodash: ^4.17.21
  lodash-es: ^4.17.21
  markdown-toc: ^1.2.0
  merge-files: ^0.1.2
  mini-css-extract-plugin: ^0.4.3
  msw: ^0.36.8
  mustache: ^4.2.0
  node-forge: ^0.10.0
  nx: 17.0.0
  nyc: ^15.1.0
  path-browserify: ^1.0.1
  postcss-import: ^14.1.0
  postcss-import-ext-glob: ^2.0.1
  postcss-loader: ^3.0.0
  prettier: ^1.19.1
  process: ^0.11.10
  prop-types: ^15.7.2
  qrcode.react: ^1.0.0
  raw-loader: ^4.0.2
  rc-tree: ^4.0.0-beta.2
  react: ^18.2.0
  react-app-polyfill: ^1.0.4
  react-codemirror2: ^6.0.0
  react-color: ^2.19.3
  react-docgen-typescript-loader: ^3.6.0
  react-dom: ^18.2.0
  react-draggable: ^4.2.0
  react-head: ^3.3.0
  react-helmet: ^5.2.1
  react-hot-loader: ^4.13.0
  react-i18next: ^11.18.5
  react-infinite-scroll-component: ^6.1.0
  react-joyride: ^2.3.0
  react-markdown: ^9.0.1
  react-notification-system: ^0.4.0
  react-redux: ^7.2.9
  react-router-dom: ^4.3.1
  react-top-loading-bar: ^1.2.0
  react-transition-group: ^4.4.1
  recharts: ^2.6.2
  reduce-reducers: ^1.0.4
  redux: ^4.0.4
  redux-devtools-extension: ^2.13.8
  redux-form: ^8.3.7
  redux-mock-store: ^1.5.4
  redux-thunk: ^2.3.0
  regenerator-runtime: ^0.13.9
  rehype-attr: ^3.0.3
  replace: ^1.1.5
  rimraf: ^3.0.2
  rollup: ^4.17.2
  rollup-plugin-generate-package-json: ^3.2.0
  rollup-plugin-polyfill-node: ^0.13.0
  rollup-plugin-scss: ^4.0.0
  rollup-plugin-styles: ^4.0.0
  rollup-plugin-svg: ^2.0.0
  semantic-ui-css: ^2.4.1
  semantic-ui-less: ^2.4.1
  semantic-ui-react: ^2.1.3
  simple-git: ^1.129.0
  slashes: ^2.0.2
  source-map-loader: ^0.2.4
  styled-components: ^4.4.1
  stylus: 0.59.0
  stylus-loader: ^7.1.0
  swr: ^2.0.0
  terser-webpack-plugin: ^5.1.1
  thread-loader: ^2.1.3
  tinycolor: 0.0.1
  tinycolor2: ^1.4.2
  ts-loader: ^6.0.1
  ts-node: ^8.5.4
  tsconfig-paths-webpack-plugin: ^3.5.2
  ua-parser-js: 0.7.28
  url-loader: ^4.1.1
  uuid: ^8.3.0
  watch: ^1.0.2
  webpack: 5.92.1
  webpack-bundle-analyzer: ^4.4.0
  webpack-cli: ^4.5.0
  webpack-dev-server: ^3.11.2
  webpack-merge: ^5.8.0
  worker-loader: ^2.0.0
  write-file-webpack-plugin: ^4.5.1
